/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Report_Requests_Controller;
import Model.Report_Requests_Model;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dpman
 */
public class Single_Row extends javax.swing.JFrame {

    /**
     * Creates new form Single_Row
     */
    public Single_Row() {
        initComponents();
         this.setLocationRelativeTo(null);
         setResizable(false);
         load_date();
    }
    
    public void load_date(){
           DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
           LocalDateTime now = LocalDateTime.now();  
           String format = dtf.format(now);  
           lbl_current_date.setText(format);
       
    }
    
    public void clearAll() {
        
        txt_proj_id.setText("");
        txt_proj_name.setText("");
        txt_completion_date.setText("");
        txt_department.setText("");
        txt_remarks.setText("");
        txt_recieved_date.setText("");
        txt_starting_date.setText("");
        txt_developer_name.setText("");
        txt_branch_name.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_proj_id1 = new javax.swing.JLabel();
        txt_proj_id = new javax.swing.JTextField();
        lbl_proj_name = new javax.swing.JLabel();
        txt_proj_name = new javax.swing.JTextField();
        lbl_proj_completion_date = new javax.swing.JLabel();
        txt_completion_date = new javax.swing.JTextField();
        lbl_proj_dept_name = new javax.swing.JLabel();
        txt_department = new javax.swing.JTextField();
        lbl_proj_id = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_remarks = new javax.swing.JTextArea();
        lbl_proj_id2 = new javax.swing.JLabel();
        lbl_proj_name1 = new javax.swing.JLabel();
        lbl_proj_completion_date1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_starting_date = new javax.swing.JTextField();
        txt_recieved_date = new javax.swing.JTextField();
        lbl_proj_completion_date2 = new javax.swing.JLabel();
        txt_request_date = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txt_branch_name = new javax.swing.JTextField();
        lbl_proj_dept_name2 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        lbl_proj_dept_name3 = new javax.swing.JLabel();
        txt_developer_name = new javax.swing.JTextField();
        lbl_current_date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_proj_id1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_id1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_id1.setText("Project ID :");

        txt_proj_id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_proj_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proj_idActionPerformed(evt);
            }
        });

        lbl_proj_name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_name.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_name.setText("Project Name :");

        txt_proj_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_proj_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proj_nameActionPerformed(evt);
            }
        });

        lbl_proj_completion_date.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_completion_date.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_completion_date.setText("Completion Date :");

        txt_completion_date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_completion_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_completion_dateActionPerformed(evt);
            }
        });

        lbl_proj_dept_name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_dept_name.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_dept_name.setText("Department :");

        txt_department.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departmentActionPerformed(evt);
            }
        });

        lbl_proj_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_id.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_id.setText("Remarks :");

        txt_remarks.setColumns(20);
        txt_remarks.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txt_remarks.setRows(5);
        jScrollPane2.setViewportView(txt_remarks);

        lbl_proj_id2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_id2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_id2.setText("Recieved Date :");

        lbl_proj_name1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_name1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_name1.setText(" Starting Date :");

        lbl_proj_completion_date1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_completion_date1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_completion_date1.setText("Project Status :");

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("                                                    Single Report Request Detail");
        jLabel1.setOpaque(true);

        txt_starting_date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_starting_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_starting_dateActionPerformed(evt);
            }
        });

        txt_recieved_date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_recieved_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_recieved_dateActionPerformed(evt);
            }
        });

        lbl_proj_completion_date2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_completion_date2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_completion_date2.setText("request Date :");

        txt_request_date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_request_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_request_dateActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Ongoing", "Done", "Blocked" }));

        txt_branch_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_branch_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_branch_nameActionPerformed(evt);
            }
        });

        lbl_proj_dept_name2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_dept_name2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_dept_name2.setText("Branch Name :");

        btn_update.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        lbl_proj_dept_name3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_proj_dept_name3.setForeground(new java.awt.Color(0, 0, 0));
        lbl_proj_dept_name3.setText("Developer Name :");

        txt_developer_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_developer_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_developer_nameActionPerformed(evt);
            }
        });

        lbl_current_date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_current_date.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_proj_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_proj_id, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_proj_name, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_proj_name, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_proj_completion_date, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_completion_date, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_proj_dept_name, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_proj_id, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_proj_completion_date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_proj_completion_date1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_request_date, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_proj_dept_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_branch_name, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_current_date, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_proj_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_proj_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_recieved_date, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_starting_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proj_dept_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_developer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_update)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_current_date, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_proj_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_proj_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_proj_name, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_proj_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_completion_date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_proj_completion_date, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_proj_dept_name, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_recieved_date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_proj_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_starting_date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_proj_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_proj_completion_date2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_request_date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_proj_completion_date1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_branch_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_proj_dept_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_proj_id, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_developer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_proj_dept_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_proj_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proj_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proj_idActionPerformed

    private void txt_proj_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proj_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proj_nameActionPerformed

    private void txt_completion_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_completion_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_completion_dateActionPerformed

    private void txt_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departmentActionPerformed

    private void txt_starting_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_starting_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_starting_dateActionPerformed

    private void txt_recieved_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_recieved_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_recieved_dateActionPerformed

    private void txt_request_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_request_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_request_dateActionPerformed

    private void txt_branch_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_branch_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_branch_nameActionPerformed

    private void txt_developer_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_developer_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_developer_nameActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        System.out.println("hii");
        String ProjId = txt_proj_id.getText();
        String ProjName = txt_proj_name.getText();
        String completion_date =  txt_completion_date.getText();
        String department = txt_department.getText();
        String remarks = txt_remarks.getText();
        String recieved_date = txt_recieved_date.getText();
        String starting_date = txt_starting_date.getText();
        String proj_status = (String) jComboBox1.getSelectedItem();
        String developers = txt_developer_name.getText();
        String branch_name = txt_branch_name.getText();
            
        Report_Requests_Model Model = new Report_Requests_Model (ProjId,ProjName,recieved_date,starting_date,completion_date,proj_status,remarks,department,branch_name,developers);
        Report_Requests_Controller controller= new Report_Requests_Controller();
     
            
        try {
            if(controller.updateReport_requests(Model)){
                
                JOptionPane.showMessageDialog(this, "The record updated");
                clearAll();
            }
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Single_Row.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Single_Row.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Single_Row.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Single_Row.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Single_Row().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_current_date;
    private javax.swing.JLabel lbl_proj_completion_date;
    private javax.swing.JLabel lbl_proj_completion_date1;
    private javax.swing.JLabel lbl_proj_completion_date2;
    private javax.swing.JLabel lbl_proj_dept_name;
    private javax.swing.JLabel lbl_proj_dept_name2;
    private javax.swing.JLabel lbl_proj_dept_name3;
    private javax.swing.JLabel lbl_proj_id;
    private javax.swing.JLabel lbl_proj_id1;
    private javax.swing.JLabel lbl_proj_id2;
    private javax.swing.JLabel lbl_proj_name;
    private javax.swing.JLabel lbl_proj_name1;
    public javax.swing.JTextField txt_branch_name;
    public javax.swing.JTextField txt_completion_date;
    public javax.swing.JTextField txt_department;
    public javax.swing.JTextField txt_developer_name;
    public javax.swing.JTextField txt_proj_id;
    public javax.swing.JTextField txt_proj_name;
    public javax.swing.JTextField txt_recieved_date;
    public javax.swing.JTextArea txt_remarks;
    public javax.swing.JTextField txt_request_date;
    public javax.swing.JTextField txt_starting_date;
    // End of variables declaration//GEN-END:variables
}
